services:
  cosmoformer-backend-service:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: cosmoformer-backend-container
    ports:
      - "8000:8000"

  cosmoformer-frontend-service:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cosmoformer-frontend-container
    ports:
      - "8080:8080"
    depends_on:
      - cosmoformer-backend-service
