apiVersion: v1
kind: Service
metadata:
  name: cosmoformer-frontend-service
  namespace: cosmoformer-app
  labels:
    app: cosmoformer
    layer: frontend
spec:
  selector:
    app: cosmoformer
    layer: frontend
  ports:
    - port: 8080
      targetPort: http
      name: http
