apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmoformer-backend-deployment
  namespace: cosmoformer-app
  labels:
    app: cosmoformer
    layer: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cosmoformer
      layer: backend
  template:
    metadata:
      labels:
        app: cosmoformer
        layer: backend
    spec:
      containers:
      - name: cosmoformer-backend
        image: quay.io/rhit_asultano/cosmoformer-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: "200m"
            memory: "3Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        readinessProbe:
          httpGet:
            path: /readycheck
            port: http
          initialDelaySeconds: 25
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: http
          initialDelaySeconds: 30
          periodSeconds: 15
