apiVersion: v1
kind: Service
metadata:
  name: cosmoformer-backend-service
  namespace: cosmoformer-app
  labels:
    app: cosmoformer
    layer: backend
spec:
  selector:
    app: cosmoformer
    layer: backend
  ports:
    - port: 8000
      targetPort: http
      name: http
